[[redirects]]
  from = "/graphql"
  to = "https://venia.magento.com/graphql"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
